baseURL = "https://cogitativejacob.github.io/minecraftautomator-hugo/"
title = "Minecraft Automator"
theme = "PaperMod"
pagination.pagerSize = 10
enableRobotsTXT = true

[params]
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  showtoc = true
  tocopen = false